version: "1.0"
info:
  model: int-scaffold
packages:
- name: MunatriFlowProject
  gitServerName: GithubOrigin
  gitUrl: https://github.com/Munatri
  gitUsername: Munatri
  gitBranch: main
- name: WmSalesforceProvider
  wpmServer: https://packages.webmethods.io
  wpmRegistry: supported
services:
- serviceName: project.munatriflow.WmSalesforceProvider.com_webmethods_cloudstreams_salesforce_v53.connections:SFAug10
  packages:
  - name: MunatriFlowProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 12.0.0.0.23
